use uttt_rs::*;

fn main() {
    let mut board = Board::new();
    let mut moves = board.generate_moves();
    let mut winner = Winner::InProgress;

    while !moves.is_empty() && winner == Winner::InProgress {
        dbg!(moves.len());
        dbg!(board.next_sub_board);
        println!("x wins: {:b}", board.sub_wins.x.0);
        println!("o wins: {:b}", board.sub_wins.o.0);
        // SAFETY: moves[0] is valid because it was generated by board.generate_moves()
        unsafe {
            board = board.advance_state(moves[0]);
        }
        moves = board.generate_moves();
        winner = board.winner();
        println!("{}", board);
    }
}
