use uttt_rs::*;

fn main() {
    let mut board = Board::new();
    let moves = board.generate_moves();

    while !moves.is_empty() {
        dbg!(moves.len());
        dbg!(board.next_sub_board);
        // SAFETY: moves[0] is valid because it was generated by board.generate_moves()
        unsafe {
            board = board.advance_state(moves[0]);
        }
        println!("{}", board);
    }
}
